# Generated by Django 5.1.7 on 2025-03-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[("full time", "full time"), ("part time", "part time")],
                default="",
                max_length=15,
            ),
            preserve_default=False,
        ),
    ]
