# Generated by Django 5.1.7 on 2025-03-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0003_job_describtion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="describtion",
            new_name="description",
        ),
        migrations.AddField(
            model_name="job",
            name="published_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
