# Generated by Django 5.1.7 on 2025-03-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0004_rename_describtion_job_description_job_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="experince",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="job",
            name="salary",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="job",
            name="vacancy",
            field=models.IntegerField(default=1),
        ),
    ]
