# Generated by Django 5.1.7 on 2025-03-20 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0005_category_job_experince_job_salary_job_vacancy"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="job.category",
            ),
            preserve_default=False,
        ),
    ]
